### ISSUE TITLE
Fatal System Error!  Trying to get property of non-object (View: /home/corehqne/admin.corehqnetwork.com/resources/views/admin/adkats/bans/index.blade.php)

### ISSUE THREAD

**Issue by mpoonuru** [AdKats/BFACP#267]
Fatal System Error!

Trying to get property of non-object (View: /home/corehqne/admin.corehqnetwork.com/resources/views/admin/adkats/bans/index.blade.php)

**Comment by Graymanflo** [comment]
I get the identical issue but when trying to list servers.

**Comment by Prophet731** [comment]
Sorry didn't see this. That error is being caused because of missing data that the application is expecting. I would need to know which line the exception is being thrown at to tell you what's wrong. Could be the bans are missing their game ID based off the record or the player data.

**Comment by mpoonuru** [comment]
Apologies for the delay. You are correct. For some reason, Game ID's are missing for some bans.
