### ISSUE TITLE
Object of class GuzzleHttp\Psr7\Response could not be converted to string

### ISSUE THREAD

**Issue by mpoonuru** [AdKats/BFACP#272]
When I try to ban or unban, I get Object of class GuzzleHttp\Psr7\Response could not be converted to string

Can you please help me?

**Comment by Prophet731** [comment]
That's probably metabans. Disable the metabans feature (clear the fields for it in the settings). See if that fixes it.

**Comment by mpoonuru** [comment]
thanks brother! Metabans down. Probably you need to consider of removing this piece.

**Comment by Prophet731** [comment]
Already planned on removing it.

**Comment by mpoonuru** [comment]
Let me know bro, if I can help you in writing code. I would like to work with you.
