### ISSUE TITLE
Just updated..now it doesnt work

### ISSUE THREAD

**Issue by wizard45** [AdKats/BFACP#278]
I have just update from version 2.0.0-rc.2 to version BFAdmin CP-v2.0.3.

After setting everything up, After a few minuets the dashboard page loaded up.  I then tried to click on the log end link and it would not let me log in.  I refreshed the page and not the page will not load up and I get this error:

Forbidden

You don't have permission to access / on this server.

Additionally, a 500 Internal Server Error error was encountered while trying to use an ErrorDocument to handle the request.

Apache Server at bfadmincp.ntccgamingclan.com Port 80

Any ideas on what I need to do now.  I recently had an issue on my older version that new people could not register on the BFadminCp website, which is why I update.

Any Ideas!???  Thank you in advance.

**Comment by Prophet731** [comment]
Make sure the file permissions are set correctly as shown in the readme file.

> Once completed upload the entire application to your webserver. Once uploaded you will need to modify some file and folder permissions. Change the files and folders permissions under app/storage recursively to 0777. This application was designed to run on a subdomain and not from a folder from the TLD. Make sure to create a subdomain and if possible have domain point to the public folder that's located under the root folder.

**Comment by wizard45** [comment]
Hello, I did that.  All permissions in app and storage show 0777

**Comment by Prophet731** [comment]
Do the same to the `public/js/builds` folder. Also make sure that the subdomain still points to the public folder. That is not a redirect link, it's should be under something called `document root`

**Comment by wizard45** [comment]
Now I am getting this error:

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator and inform them of the time the error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.

**Comment by wizard45** [comment]
Ok, so far this is what is working:

Dashboard seems to be working.

When I click on Live Scoreboard, it load for a second  and then the page clears and I get the following errors:

Fatal Error! The request couldn't complete due to a server side error. Please choose another server or retry. Notify an administrator if this error persists. 
Server is not configured yet. Please contact the site administrator.

Player list seems to work fine.

Now  I am not able to log on to bfadmin log in page.  When I try typing my username and password, I get the following error: Incorrect username, email or password. 

I tried to type admin for the user for the user box and password for the password, I get the following message:
 Your account may not be confirmed. Check your email for the confirmation link 

There is no email sent.

So there is no way for me to get into the admin page to set the setting I guess. 

Any advice.

**Comment by Prophet731** [comment]
In that version sometimes it doesn't create the admin user correctly. You just need to sign-up with your own details then go into the database and in the bfacp_users_roles table change your role to 1 and it should give you admin access. Then go to the bfacp_users table and I think there is a confirmation field and in that set it to 1 as well. I'm typing this on my phone so I don't have the tables in front of me.

**Comment by wizard45** [comment]
Both those fields already show me has admin status with the role of one.  When I try to log in, I get this message:  Incorrect username, email or password. 

I also noted that in the database, the old tables from the first version of BFadmnCp are still there as well.  But as it stands,  I cannot get into admin page.  I posted on another post here that I just found out that people could no longer register a new account on BFadminCp and you told me to update.  Could there be another issue?

**Comment by wizard45** [comment]
Additional, If you try to create a new account, It will not send an confirmation email, or it will tell me that the email address has already been used.

**Comment by wizard45** [comment]
Where can I access error logs in BFadminCP?

**Comment by Prophet731** [comment]
If you have discord you can add me and send me a link to your install and i'll see what's going on (from the public side). I would need FTP info for the private stuff. 

My discord id is `Prophet#7405 `

**Comment by wizard45** [comment]
Ok so now, people can log into the server after I do a manual confirmation.  But I still cannot get the admin links to show up on the left.  It shows me as admin in upper left hand corner.  Do i still need to re-key my SSL certificate?  Or  am i missing where the admin links on are on this page
