### ISSUE TITLE
ubuntu 16.04 BFACP only dashboard working

### ISSUE THREAD

**Issue by pedro77pl** [AdKats/BFACP#293]
Hi, 

I tried to install BFACP on fresh ubuntu 16.04 install, apache2, php5.6, mcrypt, PDO, curl, mod rewrite enabled. Installation of BFACP with composer, no errors.

Files are stored in /var/www/bfacp, ownerships, permissions for app/storage set. Connection do DB is working fine. I have adkats.bestlocker.pl subdomain pointing to web-server ip, and apache document root points to /var/www/bfacp/public.

When I enter the site, dashboard launches fine. Everything seems to work, except last bans. Problem is, none of the links work: login, live scoreboard etc. All display blank screen with 404 Not Found error. Apache logs are clean.

https://imgur.com/a/uMzIR4x

I would be grateful for any advice! I'm on Discord for fast contact: pedro77pl#5194

**Comment by pedro77pl** [comment]
Problem solved. It was Apache configuration problem.  This is working - maybe it will help someone else. BFACP files are directly in /var/www folder now.

   DocumentRoot /var/www/public
        <Directory />
                Options FollowSymLinks
                AllowOverride None
        </Directory>
        <Directory /var/www/>
                Options Indexes FollowSymLinks
                AllowOverride All
                Require all granted
        </Directory>

**Comment by Prophet731** [comment]
Glad you were able to figure it out. However, I don't know why I never got a notification that this was created.
